#!/bin/sh

set -e

# allow overriding resolv.conf location for testing
RESOLV_CONF=${RESOLV_CONF:-/etc/resolv.conf}

. /etc/adblock.conf

layout=unknown
case `uname -s` in
  FreeBSD )
    layout=freebsd ;;
  OpenBSD )
    layout=openbsd ;;
  Linux )
    if test -f /etc/debian_version || test -f /etc/devuan_version; then
      layout=debian
    fi
    ;;
esac

case $layout in
  debian)
    NAMED_CONF=${NAMED_ETC}/named.conf.options
    ;;
  freebsd)
    NAMED_CONF=${NAMED_ETC}/named.conf
    ;;
  *)
    echo "Bad layout: $layout" 1>&2
    exit 1
    ;;
esac

actual_ns=`egrep '^\s*nameserver' $RESOLV_CONF |awk '{print $2}'`

if test -n "$PASSTHROUGH_NAMESERVERS"; then
  for ns in $PASSTHROUGH_NAMESERVERS 127.0.0.1; do
    for ans in $actual_ns; do
      if test "$ans" = "$ns"; then
        exit
      fi
    done
  done
fi

inplace_sed() {
  if test `uname -s` = Linux; then
    sed -i "$@"
  else
    # BSD
    sed -i "" "$@"
  fi
}

forwarders() {
  printf 'forwarders {'
  for ans in $actual_ns; do
    printf "$ans; "
  done
  printf '};'
}

#set -x
case $reason in
  "BOUND"|"RENEW"|"REBIND"|"REBOOT")
    # use DNS servers obtained by dhclient as forwarders
    # don't rely on spaces inside forwarders declaration in case the previous run left a blank forwarders line
    # note: -E and -i switches to sed are non-portable and won't work on openbsd, in particular 
    forwarders
    inplace_sed -E -e 's/[ \t]*forwarders \{.*\};/'"`forwarders`"/ $NAMED_CONF
    # tell name server to use new forwarders
    rndc reload
    # replace nameserver declarations in resolv.conf
    tempfile=`mktemp -t dhclient_hook.XXXXXX`
    <$RESOLV_CONF sed -e '/^nameserver/d' > $tempfile
    echo nameserver 127.0.0.1 >> $tempfile
    # copy instead of moving to preserve resolv.conf's permissions and ownership
    cp $tempfile $RESOLV_CONF
    rm $tempfile
    ;;
esac
